### ISSUE TITLE
recommendation/ not an issue: sequence boundaries of significant attractive/repulsive interactions

### ISSUE THREAD

**Issue by jiyoungyoun** [idptools/finches#2]
We have proteins with long IDR regions (>1300aa) and have used the google collab, which looks fantastic. The heat map looks great but is difficult to see a clear boundaries are where the attractive and repulsive forces end. Is it possible to extract the raw information used for heat map visualization so we can determine the sequence boundaries?

**Comment by alexholehouse** [comment]
Hey Ji-Young!

Absolutely; I've added in a checkbox to the colab notebook now where, if set to True, the data for intermap gets downloaded as a CSV (with first row/column giving the index). Let me know if this works and/or if there's additional stuff that would be useful. One thing to note is we don't zero out the matrix values for folded domains in that downloaded matrix.

**Comment by jiyoungyoun** [comment]
WOW! That was remarkably fast. 

I refreshed google collab and tested this 'download' function. It looks like there is an error with 'mf' not being defined. 
<img width="832" alt="Screenshot 2024-06-06 at 9 21 41 PM" src="https://github.com/idptools/finches/assets/45950915/521d03e4-5936-4579-a847-cc96403a55a0">

**Comment by alexholehouse** [comment]
Ah - I must have messed up something in the initialization cell, sorry will fix this at some point soon, cancelled international flights willing…


~alex

Sent from my iPhone


________________________________

**Comment by jiyoungyoun** [comment]
No rush, Alex! Hope you make it to your destination -

**Comment by alexholehouse** [comment]
Hello - hmm so it seems to work, but perhaps you didn't run the first setup cell? This is where all the initialization happens and needs to be run once first before the analysis is run. 

That said, I've updated the notebook again to remove this, so now there is only one cell that can be run, and should work without issue (although not the FIRST time you run the analysis it will take ~1 min because it has to install finches, but after that new sequences can be analyzed in seconds!)

**Comment by jiyoungyoun** [comment]
Fantastic - I can download the matrix of the input data now. This is very useful - thanks, Alex!

**Comment by alexholehouse** [comment]
No worries! Yeah, for bigger proteins, this takes longer and longer to run, but it should be stable up to a few thousand amino acids at least... There's an unavoidable n^2 component in the underlying algorithm, but thankfully _most_ proteins are not 3000+ amino acids! On my local MBP the time it takes for longer sequences is MUCH much lower than on the colab notebooks, so we're certainly CPU bound here. Anyway, happy to add features as needed!
